Sprint 1/step 1 - промежуточная сдача
limeman14/YandexPracticum-react-burger pull request #1
Opened 2023-10-23 13:02 UTC by limeman14

2023-10-23 14:29 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа. 🔥

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику, переделать `span` в ссылку.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

- Отметил замечания в коде.

- Советую почитать про нейминг в реакте. <https://github.com/airbnb/javascript/tree/master/react#naming>, измените названия файлов на `PascalCase`;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/mainIngredient/mainIngredient.jsx
> +    <li className='mb-4' style={{display: 'flex', alignItems: 'center'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/appHeader/appHeader.jsx
> +        <RightSection/>
**Надо исправить:**

здесь и далее.

Не нужно так сильно дробить код на компоненты, left и right section не нужно выносить в компоненты.
там ведь нету уникальных элементов, тем более вы уже сделали компонент для ссылки `MenuItem`.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/appHeader/menuItem/menuItem.jsx
> +    <span className={`mt-4 mb-4 pl-5 pr-5 ${styles.menuItem}`}>
**Надо исправить:**

В компоненте App-header требуется поправить семантику, переделать `span` в ссылку.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/common/mainLayout/mainLayout.jsx
> +}
**Надо исправить:**

Не стоит выносить в отдельный компонент такие маленькие куски кода. Вы уже можете заметить что у вас появилось очень много компонентов, это не очень хорошо, т.к. трудно будет в будущем дорабатывать и дебажить код.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/bunIngredient/bunIngredient.jsx
> +export function BunIngredient({bun, position}) {
**Надо исправить:**

У вас ведь уже есть компонент `ConstructorElement`, не стоит создавать компонент ради компонента, вам лучше напрямую использовать этот компонент))

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/createOrderPanel/createOrderPanel.jsx
> +export function CreateOrderPanel({sum, onCreateOrderClick}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/mainIngredient/mainIngredient.jsx
> +export function MainIngredient({item}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/burgerConstructor.jsx
> +    '60666c42cc7b410027a1a9bc', '60666c42cc7b410027a1a9bb', '60666c42cc7b410027a1a9bb', '60666c42cc7b410027a1a9b6'])
**Можно лучше:**

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/burgerConstructor.jsx
> +      <ul className='text' style={{maxHeight: '464px', overflowY: 'auto', scrollbarWidth: 'thin'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/createOrderPanel/createOrderPanel.jsx
> +      <div style={{display: "flex", alignItems: 'baseline'}} className='mr-10'>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerIngredients/burgerIngredients.jsx
> +      <div className='mt-5' style={{display: 'flex'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/ingredientCatalogSection/ingredientCatalogSection.jsx
> +      <ul className='pt-6 pr-4 pb-10 pl-4' style={{display: "grid", gridTemplateColumns: '272px 272px', gap: '32px 24px'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/ingredientCatalogSection/ingredientCard/ingredientCard.jsx
> +      {count && <Counter count={count}/>}
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerIngredients/burgerIngredients.jsx
> +  const { bun, sauce, main} = _.groupBy(data, ing => ing.type)
**Вы молодец:**

Хорошое решение.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerIngredients/burgerIngredients.jsx
> +export function BurgerIngredients({data}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/burgerConstructor.jsx
> +export function BurgerConstructor({data}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/ingredientCatalogSection/ingredientCard/ingredientCard.jsx
> +export function IngredientCard({imageSrc, price, name, count}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-23 14:29 UTC, ArslanMustafin commented on src/components/constructor/ingredientCatalogSection/ingredientCatalogSection.jsx
> +export function IngredientCatalogSection({headingTitle, items}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-23 15:36 UTC, limeman14 commented on src/components/constructor/burgerConstructor/mainIngredient/mainIngredient.jsx
> +    <li className='mb-4' style={{display: 'flex', alignItems: 'center'}}>
Ack

2023-10-23 15:49 UTC, limeman14 commented on src/components/constructor/burgerConstructor/burgerConstructor.jsx
> +export function BurgerConstructor({data}) {
ack

2023-10-23 15:49 UTC, limeman14 commented on src/components/constructor/burgerIngredients/burgerIngredients.jsx
> +export function BurgerIngredients({data}) {
ack

2023-10-23 15:49 UTC, limeman14 commented on src/components/constructor/ingredientCatalogSection/ingredientCard/ingredientCard.jsx
> +export function IngredientCard({imageSrc, price, name, count}) {
ack

2023-10-23 15:50 UTC, limeman14 commented on src/components/constructor/ingredientCatalogSection/ingredientCatalogSection.jsx
> +export function IngredientCatalogSection({headingTitle, items}) {
ack

2023-10-23 15:51 UTC, limeman14 commented on src/components/common/mainLayout/mainLayout.jsx
> +}
спасибо, поправил

2023-10-23 15:51 UTC, limeman14 commented on src/components/constructor/burgerConstructor/createOrderPanel/createOrderPanel.jsx
> +export function CreateOrderPanel({sum, onCreateOrderClick}) {
ack

2023-10-23 15:51 UTC, limeman14 commented on src/components/constructor/burgerConstructor/mainIngredient/mainIngredient.jsx
> +export function MainIngredient({item}) {
ack

2023-10-23 15:56 UTC, limeman14 commented on src/components/constructor/burgerConstructor/createOrderPanel/createOrderPanel.jsx
> +      <div style={{display: "flex", alignItems: 'baseline'}} className='mr-10'>
ack

2023-10-23 15:57 UTC, limeman14 commented on src/components/constructor/burgerConstructor/burgerConstructor.jsx
> +      <ul className='text' style={{maxHeight: '464px', overflowY: 'auto', scrollbarWidth: 'thin'}}>
ack

2023-10-23 15:57 UTC, limeman14 commented on src/components/constructor/ingredientCatalogSection/ingredientCatalogSection.jsx
> +      <ul className='pt-6 pr-4 pb-10 pl-4' style={{display: "grid", gridTemplateColumns: '272px 272px', gap: '32px 24px'}}>
ack

2023-10-23 15:57 UTC, limeman14 commented on src/components/constructor/burgerIngredients/burgerIngredients.jsx
> +      <div className='mt-5' style={{display: 'flex'}}>
ack

2023-10-23 15:57 UTC, limeman14 commented on src/components/constructor/ingredientCatalogSection/ingredientCard/ingredientCard.jsx
> +      {count && <Counter count={count}/>}
ack

2023-10-23 16:04 UTC, limeman14 commented on src/components/constructor/burgerConstructor/burgerConstructor.jsx
> +    '60666c42cc7b410027a1a9bc', '60666c42cc7b410027a1a9bb', '60666c42cc7b410027a1a9bb', '60666c42cc7b410027a1a9b6'])
спасибо за наводку, поправил, хотел просто отобразить конкретную корзину с макета, а не все ингредиенты из data

2023-10-23 17:02 UTC, limeman14 commented on src/components/appHeader/appHeader.jsx
> +        <RightSection/>
ack

2023-10-23 17:02 UTC, limeman14 commented on src/components/appHeader/menuItem/menuItem.jsx
> +    <span className={`mt-4 mb-4 pl-5 pr-5 ${styles.menuItem}`}>
done

2023-10-23 17:06 UTC, limeman14 commented on src/components/constructor/burgerConstructor/bunIngredient/bunIngredient.jsx
> +export function BunIngredient({bun, position}) {
В этом компоненте много кода по определению отступов, модификации имени, не хотелось бы выносить его в родительский BurgerConstructor

2023-10-24 04:31 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличая работа. 🔥

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Все замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- Переименуйте папки в соответствии с названиями компонентов (в `kebab-case`, чтобы в дальнейшем не было проблемы с переименованием). Проверьте, что в системе контроля версий правильный регистр и при необходимости измените <https://noteskeeper.ru/heritage/672/>.

- Требуется полное описание структуры ингредиента, а не propTypes.array.
  А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
  ```

  Во многих компонентах будет дублироваться описание PropTypes ингредиента.
  Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

- Отметил замечания в коде.

### **Сделает код лучше:**

- Уже сейчас у вас достаточно много компонентов, попробуйте использовать такую структуру файлов (<https://disk.yandex.com/i/soGz947XvCfsTQ>):

  ```js
  // test-component/components/index.js

  export { default as ChildComponent } from './child-component/сhild-сomponent.jsx';

  // test-component/test-component.jsx

  import React from 'react';
  import { ChildComponent } from './components';

  const TestComponent = () => {
    return (
      <div>
        <ChildComponent />
      </div>
    );
  };

  export default TestComponent;
  ```

  Старайтесь сильно не дробить код на компоненты, это тоже не очень хорошо, при тестировании замучаетесь писать тесты). А также не стоит делать сильную вложенность, вложенность на скрине оптимальна (бывают конечно исключения, но в данном проекте таких вроде бы нет).

- В прошлой проверке я сказал вам изменить названия файлов, и написать их в `PascalCase`, этот вариант допустим и даже где-то активно используется, но существует ещё вариант с `kebab-case`. Обычно каждая команда использует тот вариант, который ей больше нравится, очень часто это вариант с `kebab-case`, потому что он легко редактируется, и не нужно потом парится с изменением регистра файлов и папок), поэтому тут можете сами решить какой вам больше нравится.

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/BurgerConstructor.jsx
> +  }
**Надо исправить:**

В данном случае лучше использовать `useMemo`, а не функцию.  

```js
  const totalSum = useMemo(() => {
    const mainIngredientsSum = cart.map(cartItem => cartItem.price).reduce((a, b) => a + b, 0);
    return mainIngredientsSum + 2 * bun.price;
  }, [cart, bun]);
```

В целом, вызов функций непосредственно в JSX допустим, но это может привести к проблемам с читаемостью кода и эффективностью. Иногда бывает более чистым и безопасным вычислить значения заранее и передать их как пропсы.

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/BurgerConstructor.jsx
> +  const { bun, cart } = useMemo(() => {
**Можно лучше:**

стоит переименовать `cart` в  `ingredients`, т.к. тут именно ингредиенты, а не корзина.

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/bunIngredient/BunIngredient.jsx
> +    </div>
**Надо исправить:**

Вы ведь можете просто вынести это следующим образом: 

```js
 <div className="pl-8 mb-4">
   <ConstructorElement
      text={`${bun.name} (верх)`}
      thumbnail={bun.image}
      price={bun.price}
      type="top"
      isLocked
    />
 </div>
```

 Ну и аналогично для другой булки.

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/mainIngredient/MainIngredient.jsx
> +export function MainIngredient ({ item }) {
**Можно лучше:**

Лучше переименовать в `BurgerIngredient`.

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerIngredients/ingredientCatalogSection/IngredientCatalogSection.jsx
> +          return <IngredientCard key={index}
**Можно лучше:**

тут вроде бы всегда будет уникальный `id` у ингредиентов, поэтому в качестве `key` лучше использовать его.

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/appHeader/menuItem/MenuItem.jsx
> +export function MenuItem ({ icon, text, active }) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/BurgerConstructor.jsx
> +  data: PropTypes.array.isRequired
**Надо исправить:**

Здесь и в других компонентах.

Требуется полное описание структуры ингредиента, а не propTypes.array.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

Во многих компонентах будет дублироваться описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/mainIngredient/MainIngredient.jsx
> +  item: PropTypes.object.isRequired
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.

```js
data: ingredientType.isRequired;
```

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerIngredients/BurgerIngredients.jsx
> +  data: PropTypes.array.isRequired
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.any.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

2023-10-24 04:31 UTC, ArslanMustafin commented on src/components/constructor/burgerIngredients/ingredientCatalogSection/IngredientCatalogSection.jsx
> +  items: PropTypes.array.isRequired
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.any.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

2023-10-24 04:33 UTC, ArslanMustafin commented on src/components/constructor/burgerConstructor/bunIngredient/bunIngredient.jsx
> +export function BunIngredient({bun, position}) {
Показала в новом комментарии как это можно сделать, да и вроде бы, это не так громоздко.

2023-10-25 15:29 UTC, merged